---
title: "Mini-challenge 3"
description: |
  A short description of the post.
author:
  - name: Qian Ziwei
    url: https://example.com/norajones
date: 07-11-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.retina = 3,
                      echo = TRUE,
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

# 1. Overview

---

### 1.1 Background

In the country island of Kronos, the increasing noxious effects on health and farming have been related to the uncontrolled activity of GAStech, a natural gas operator, supported by corrupt government officials. On January 20th, 2014, a corporate meeting is held to celebrate the new-found fortune because of the initial public offering of the company. However, a series of rare events occur that lead to the disappearance of several employees. The Protectors of Kronos (POK), a social movement organization that has been fighting against water contamination and government corruption, is suspected in the disappearance.

As analysts, we were assigned with several tasks in order to identify risks and how they could have been mitigated more effectively.

### 1.2 Literature review


### 1.3 Objective

Using data and visual analytics to evaluate the changing levels of risk to the public and recommend actions for first responder:

* Distinguish meaningful event reports from typical chatter from junk or spam.

* Evaluate the level of the risk to the public evolves over the course of the evening. Consider the potential consequences of the situation and the number of people who could be affected.
Determine the appropriate location for first responders.

* The differences between dealing with this challenge in 2014 and dealing with it now.

### 1.4 Question 1

### 1.5 Question 2

### 1.6 Question 3

### 1.7 Question 4


---


